// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTGvg-Lif1JlUcgSW2xzh2yaTs3-cjkE',
    appId: '1:845473424065:android:edd44cb947ee1251086a40',
    messagingSenderId: '845473424065',
    projectId: 'around-museo-de-baler-bfb54',
    storageBucket: 'around-museo-de-baler-bfb54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kICqvOt3UByA_AN4clZiKeM7VkHcuQE',
    appId: '1:845473424065:ios:0b70934e884df903086a40',
    messagingSenderId: '845473424065',
    projectId: 'around-museo-de-baler-bfb54',
    storageBucket: 'around-museo-de-baler-bfb54.appspot.com',
    androidClientId: '845473424065-068g0f2i0i4grr07fb70nlfpir5v7dkv.apps.googleusercontent.com',
    iosClientId: '845473424065-hduuaa3nqet1hbcpgkb5i6okfjn91pe8.apps.googleusercontent.com',
    iosBundleId: 'com.clsu.bsit.aroundMuseoDeBalerMobileApp',
  );

}